name: Build and Release

on:
  push:
    tags:
      - "v*"

env:
  GODOT_VERSION: 4.5.0-dev.1

jobs:
  build:
    name: Build-${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: Linux
            export-preset: linux
            export-type: release
            export-path: build/linux

          - name: Windows
            export-preset: windows
            export-type: release
            export-path: build/windows

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Godot - Setup
        uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{ env.GODOT_VERSION }}
          use-dotnet: false
          include-templates: true

      - name: Copy export_presets.cfg
        shell: bash
        run: cp .github/dist/export_presets.cfg .

      - name: Godot Import Assets
        shell: bash
        run: godot --headless --import

      - name: Make build path
        shell: bash
        run: |
          mkdir -p ${{ matrix.export-path }}
          ls -lah ${{ matrix.export-path }}

      - name: Godot Export ${{ matrix.name }}
        shell: bash
        run: godot --headless --export-${{ matrix.export-type }} "${{ matrix.export-preset }}"

      - name: Compress Artifacts
        run: |
          zip Freecell-${{ matrix.name }}.zip ${{ matrix.export-path }}/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-artifacts
          path: Freecell-${{ matrix.name }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: artifacts/*.zip
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
